import type { Challenge } from "./types"

export const challenges: Challenge[] = [
  {
    id: "1",
    title: "季節外れの服を収納",
    description: "今の季節に着ない服を整理して、収納ボックスにしまいましょう。クローゼットがすっきりします。",
    type: "clothing",
    expReward: 25,
    itemReward: "収納の魔法箱",
    itemType: "box",
    completed: false,
  },
  {
    id: "2",
    title: "古着の断捨離",
    description: "1年以上着ていない服を5着以上選んで処分または寄付しましょう。新しい服のスペースを作ります。",
    type: "clothing",
    expReward: 25,
    itemReward: "整理の巻物",
    itemType: "scroll",
    completed: false,
  },
  {
    id: "3",
    title: "靴下の整理整頓",
    description: "バラバラになった靴下をペアにして、きれいに畳んで収納しましょう。",
    type: "socks",
    expReward: 25,
    itemReward: "ペアの護符",
    itemType: "amulet",
    completed: false,
  },
  {
    id: "4",
    title: "ハンガーの統一",
    description: "クローゼットのハンガーを同じタイプに統一して、見た目も機能も向上させましょう。",
    type: "clothing",
    expReward: 25,
    itemReward: "整頓の葉",
    itemType: "leaf",
    completed: false,
  },
  {
    id: "5",
    title: "アクセサリーの整理",
    description: "散らかったアクセサリーを種類ごとに分けて、専用ケースに収納しましょう。",
    type: "other",
    expReward: 25,
    itemReward: "宝石の小箱",
    itemType: "gem",
    completed: false,
  },
  {
    id: "6",
    title: "クローゼットの掃除",
    description: "クローゼット内を掃除機で清掃し、棚を拭いてきれいにしましょう。",
    type: "clothing",
    expReward: 25,
    itemReward: "清浄の水晶",
    itemType: "crystal",
    completed: false,
  },
]

